
== synatainer

Synapse Maintenance Container

'''

Docker container with tools for synapse & postgres database maintenance

Matrix room: https://matrix.to/#/#synatainer:c-base.org[#synatainer:c-base.org]

=== What is this?

This docker container is based on https://github.com/matrix-org/rust-synapse-compress-state[] and contains besides the state compressor additional tools and scripts for automated synapse and postgres maintenance.

This container is under havy development, so things may change.

=== Tools and Scripts

* [*] synapse_auto_compressor
* [*] synapse_compress_state
* [ ] synatainer.sh
* [ ] background-service.sh
* [*] purge_rooms_no_local_members.sh
* [*] remote_cache_purge.sh
* [ ] purge_history.sh
* [*] vacuum-db.sh

=== Quick Start Usage Examples

Get/update the container:

    docker pull registry.gitlab.com/mb-saces/synatainer:testing

Run just the auto compressor:

    docker run -it --rm -v /run/postgresql/.s.PGSQL.5432:/run/postgresql/.s.PGSQL.5432 registry.gitlab.com/mb-saces/synatainer:testing synapse_auto_compressor -p "postgresql://db_user:db_password@%2Frun%2Fpostgresql/synapse" -n 100 -c 500

Run the automagic maintenance script:

    docker run -it --rm -v /run/postgresql/.s.PGSQL.5432:/run/postgresql/.s.PGSQL.5432 -v /local/path/to/conf:/conf/synatainer.conf registry.gitlab.com/mb-saces/synatainer:testing synatainer.sh

Run the automagic maintenance background service:

    docker run -it --rm -v /run/postgresql/.s.PGSQL.5432:/run/postgresql/.s.PGSQL.5432 -v /local/path/to/conf:/conf/synatainer.conf registry.gitlab.com/mb-saces/synatainer:testing background-service.sh

=== Configuration

Config can be passed as file or environment variables. +
Mount the config file to /conf/synatainer.conf

    docker run -it --rm -v /local/path/to/conf:/conf/synatainer.conf ...

==== Database Configuration

===== Password File (recommended)

The password file should contain lines of the following format:

    hostname:port:database:username:password

Mount this file to /conf/pgpassword with permission 0600. Alternatively you can mount the file to an arbitrary location and set the envirionment variable `PGPASSFILE` accordingly.

===== Environment Variables

`DB_HOST` postgres host name +
`DB_NAME` postgres database name +
`DB_USER` postgres database user +
`PGPASSWORD` postgres database password

==== Synapse Configuration

`BEARER_TOKEN` access token with serveradmin privileges +
`SYNAPSE_HOST` synapse admin api, default http://127.0.0.1:8008

==== Background Service Configuration

The background service is driven by cron, configuring it via environment variables can be a beast. Lets see how it evolves… +
The default configuration should be fine for average servers.

To enable email notification, set

`MAILTO` recipient address +
`MAILFROM` use this sender adress +
`SMTPHOST` mailserver to use

Default schedule:

[source,shell]
----
include::scripts/background-service.sh[tag=doc]
----

To gain full control, you can mount your own /etc/crontabs/root file.

==== Miscellaneous Configuration

Enironment variables:

`MEDIA_MAX_AGE` number of days before remote media  gets deleted, default 90 +
`HISTORY_MAX_AGE` number of days before history gets deleted, default 180 +
`STATE_AUTOCOMPRESSOR_CHUNKS_TO_COMPRESS` default 100 +
`STATE_AUTOCOMPRESSOR_CHUNK_SIZE` default 500 +
`STATE_AUTOCOMPRESSOR_CHUNKS_TO_COMPRESS_BIG` default 300 +
`STATE_AUTOCOMPRESSOR_CHUNK_SIZE_BIG` default 1500

Example config file:

----

# Comment
BEARER_TOKEN=<token>
DB_HOST=/run/postgresql
DB_NAME=synapse
DB_USER=synapse_user
PGPASSWORD=very_secret
SYNAPSE_HOST=http://127.0.0.1:8008
MEDIA_MAX_AGE=90
HISTORY_MAX_AGE=180
STATE_AUTOCOMPRESSOR_CHUNKS_TO_COMPRESS=100
STATE_AUTOCOMPRESSOR_CHUNK_SIZE=500

----

== Scripts explained

background-service.sh::
[source,shell]
----
include::scripts/background-service.sh[tag=doc]
----

synatainer.sh::
[source,shell]
----
include::scripts/synatainer.sh[tag=doc]
----

purge_rooms_no_local_members.sh::
[source,shell]
----
include::scripts/purge_rooms_no_local_members.sh[tag=doc]
----

remote_cache_purge.sh::
[source,shell]
----
include::scripts/remote_cache_purge.sh[tag=doc]
----

purge_history.sh::
[source,shell]
----
include::scripts/purge_history.sh[tag=doc]
----

vacuum-db.sh::
[source,shell]
----
include::scripts/vacuum-db.sh[tag=doc]
----
